In [1]:
import pickle
import pandas as pd
import numpy as np
from sklearn.svm import SVC, SVR
import os

In [2]:
TEST_DATA_ROOT = '~/workspace/datarobot-user-models/tests/testdata'
BINARY_DATA = os.path.join(
    TEST_DATA_ROOT, 'iris_binary_training.csv'
)
REGRESSION_DATA = os.path.join(
    TEST_DATA_ROOT, 'boston_housing.csv'
)
MULTICLASS_DATA = os.path.join(
    TEST_DATA_ROOT, 'Skyserver_SQL2_27_2018 6_51_39 PM.csv'
)

bin_X = pd.read_csv(BINARY_DATA)
bin_y = bin_X.pop('Species')

reg_X = pd.read_csv(REGRESSION_DATA)
reg_y = reg_X.pop('MEDV')

multi_X = pd.read_csv(MULTICLASS_DATA)
multi_y = multi_X.pop('class')

In [3]:
bin_model = SVC(probability=True)
bin_model.fit(bin_X, bin_y)

reg_model = SVR()
reg_model.fit(reg_X, reg_y)

multi_model = SVC(probability=True)
multi_model.fit(multi_X, multi_y)

SVC(probability=True)

In [4]:
print(bin_model.predict_proba(bin_X))
print(reg_model.predict(reg_X))
print(multi_model.predict_proba(multi_X))

[[0.98010965 0.01989035]
 [0.98260226 0.01739774]
 [0.98476801 0.01523199]
 [0.98656393 0.01343607]
 [0.98811647 0.01188353]
 [0.98934518 0.01065482]
 [0.99059878 0.00940122]
 [0.99152599 0.00847401]
 [0.99237124 0.00762876]
 [0.99302076 0.00697924]
 [0.99354579 0.00645421]
 [0.99403714 0.00596286]
 [0.99443788 0.00556212]
 [0.99478744 0.00521256]
 [0.99490279 0.00509721]
 [0.99500875 0.00499125]
 [0.99515943 0.00484057]
 [0.99520254 0.00479746]
 [0.99506728 0.00493272]
 [0.99503614 0.00496386]
 [0.99479596 0.00520404]
 [0.99456792 0.00543208]
 [0.99434911 0.00565089]
 [0.9936349  0.0063651 ]
 [0.99299618 0.00700382]
 [0.99221488 0.00778512]
 [0.99112952 0.00887048]
 [0.98979813 0.01020187]
 [0.988097   0.011903  ]
 [0.98586649 0.01413351]
 [0.98292052 0.01707948]
 [0.97887652 0.02112348]
 [0.97414791 0.02585209]
 [0.96747312 0.03252688]
 [0.9592219  0.0407781 ]
 [0.94847509 0.05152491]
 [0.93562636 0.06437364]
 [0.91782196 0.08217804]
 [0.89631952 0.10368048]
 [0.15438228 0.84561772]


[[0.06629009 0.13380734 0.79990257]
 [0.75830118 0.07147804 0.17022078]
 [0.75654658 0.07102188 0.17243155]
 ...
 [0.06034682 0.1561186  0.78353459]
 [0.75744037 0.07298353 0.16957611]
 [0.75744033 0.07298354 0.16957614]]


In [5]:
FIXTURE_ROOT = '~/workspace/datarobot-user-models/tests/fixtures/drop_in_model_artifacts'
with open(os.path.expanduser(os.path.join(FIXTURE_ROOT, 'sklearn_bin.pkl')), 'wb') as picklefile:
    pickle.dump(bin_model, picklefile)
with open(os.path.expanduser(os.path.join(FIXTURE_ROOT, 'sklearn_reg.pkl')), 'wb') as picklefile:
    pickle.dump(reg_model, picklefile)
with open(os.path.expanduser(os.path.join(FIXTURE_ROOT, 'sklearn_multi.pkl')), 'wb') as picklefile:
    pickle.dump(multi_model, picklefile)